# Generated by Django 3.2.7 on 2023-03-21 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('publié', models.BooleanField(default=False, verbose_name='Publié')),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('derniere_modification', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='article')),
                ('categorie', models.CharField(choices=[('CO', 'Construction'), ('CM', 'Commerciale'), ('IN', 'Innovation'), ('ST', 'Structure'), ('SE', 'Securite')], max_length=2)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('description1', models.TextField(verbose_name='Description1')),
                ('description2', models.TextField(verbose_name='Description2')),
                ('description3', models.TextField(verbose_name='Description3')),
                ('image', models.ImageField(upload_to='Option')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('post_nom', models.CharField(max_length=255, verbose_name='Post nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prenom')),
                ('genre', models.CharField(max_length=2, verbose_name='Genre')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('pourcentage', models.IntegerField(verbose_name='Pourcentage')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('nom_responsable', models.CharField(max_length=255, verbose_name='Nom de responsable')),
                ('religion', models.CharField(max_length=255, verbose_name='Religion')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description1', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Formation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='Commenatire')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalama.article')),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
    ]
